{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "ssmglobal",
      "Effect": "Allow",
      "Action" : [
        "ssm:DescribeParameters"
      ],
      "Resource": "arn:aws:ssm:eu-west-2:${account_id}:*"
    },
    {
      "Sid" : "ssm",
      "Effect": "Allow",
      "Action": [
          "ssm:GetParameter"
      ],
      "Resource" : [
          "arn:aws:ssm:eu-west-2:${account_id}:parameter/mgmt/cost_centre",
          "arn:aws:ssm:eu-west-2:${account_id}:parameter/mgmt/trusted_ips",
          "arn:aws:ssm:eu-west-2:${account_id}:parameter/mgmt/external_ips",
          "arn:aws:ssm:eu-west-2:${account_id}:parameter/mgmt/management_account"
      ]
    },
    {
      "Sid": "iam",
      "Effect": "Allow",
      "Action": [
        "iam:AddRoleToInstanceProfile",
        "iam:AttachRolePolicy",
        "iam:CreateInstanceProfile",
        "iam:CreatePolicy",
        "iam:CreateRole",
        "iam:DeletePolicy",
	    "iam:DeletePolicyVersion",
        "iam:DeleteRole",
        "iam:DeleteRolePolicy",
        "iam:DetachRolePolicy",
        "iam:GetPolicy",
        "iam:GetPolicyVersion",
        "iam:GetRole",
        "iam:ListAttachedRolePolicies",
        "iam:ListInstanceProfilesForRole",
        "iam:ListPolicyVersions",
        "iam:PassRole",
        "iam:PutRolePolicy",
        "iam:TagRole",
        "iam:UpdateAssumeRolePolicy",
        "iam:UpdateRole",
        "iam:CreateServiceLinkedRole",
        "iam:CreatePolicyVersion",
        "iam:CreateOpenIDConnectProvider",
        "iam:GetOpenIDConnectProvider",
        "iam:DeleteOpenIDConnectProvider"
      ],
      "Resource": [
        "arn:aws:iam::${account_id}:role/aws-service-role/guardduty.amazonaws.com/AWSServiceRoleForAmazonGuardDuty",
        "arn:aws:iam::${account_id}:role/aws-service-role/ecs.amazonaws.com/AWSServiceRoleForECS",
        "arn:aws:iam::${account_id}:role/aws-service-role/elasticloadbalancing.amazonaws.com/AWSServiceRoleForElasticLoadBalancing",
        "arn:aws:iam::${account_id}:role/aws-service-role/rds.amazonaws.com/AWSServiceRoleForRDS",
        "arn:aws:iam::${account_id}:role/aws-service-role/ecs.amazonaws.com/AWSServiceRoleForECS",
        "arn:aws:iam::${account_id}:role/aws-service-role/elasticache.amazonaws.com/AWSServiceRoleForElastiCache*",
        "arn:aws:iam::${account_id}:policy/TDRCloudwatch${environment}",
        "arn:aws:iam::${account_id}:role/TDRCloudTrail${environment}",
        "arn:aws:iam::${account_id}:oidc-provider/auth.${sub_domain}.nationalarchives.gov.uk",
        "arn:aws:iam::${account_id}:oidc-provider/auth.${sub_domain}.nationalarchives.gov.uk/auth/realms/tdr",
        "arn:aws:iam::${account_id}:policy/TDRDbMigrationLambdaPolicy${environment}",
        "arn:aws:iam::${account_id}:role/TDRDbMigrationLambdaRole${environment}",
        "arn:aws:iam::${account_id}:policy/TDRConfig${environment}",
        "arn:aws:iam::${account_id}:role/TDRConfig${environment}",
        "arn:aws:iam::${account_id}:policy/TDRSNSPublish${environment}",
        "arn:aws:iam::${account_id}:role/Custodian*",
        "arn:aws:iam::${account_id}:policy/TDRCustodian*",
        "arn:aws:iam::${account_id}:role/TDRCognitoAuthorisedRole${environment}",
        "arn:aws:iam::${account_id}:policy/CognitoAuthPolicy${environment}",
        "arn:aws:iam::${account_id}:policy/TDRYaraAvPolicy",
        "arn:aws:iam::${account_id}:role/TDRYaraAvRole"
      ]
    },
    {
      "Sid" : "kms",
      "Effect": "Allow",
      "Action" : [
        "kms:CreateAlias",
        "kms:CreateKey",
        "kms:CreateGrant",
        "kms:Decrypt",
        "kms:DeleteAlias",
        "kms:DeleteKey",
        "kms:DescribeKey",
        "kms:EnableKey",
        "kms:EnableKeyRotation",
        "kms:Encrypt",
        "kms:GetKeyPolicy",
        "kms:GetKeyRotationStatus",
        "kms:ListAliases",
        "kms:ListGrants",
        "kms:ListKeyPolicies",
        "kms:ListKeys",
        "kms:ListResourceTags",
        "kms:ListRetirableGrants",
        "kms:PutKeyPolicy",
        "kms:RevokeGrant",
        "kms:ScheduleKeyDeletion",
        "kms:TagResource",
        "kms:UntagResource",
        "kms:UpdateAlias",
        "kms:UpdateKeyDescription"
      ],
      "Resource": "*"
    },
    {
      "Sid": "s3",
      "Effect": "Allow",
      "Action": [
        "s3:CreateBucket",
        "s3:DeleteBucket",
        "s3:DeleteBucketPolicy",
        "s3:DeleteObject",
        "s3:DeleteObjectTagging",
        "s3:DeleteObjectVersion",
        "s3:DeleteObjectVersionTagging",
        "s3:GetAccelerateConfiguration",
        "s3:GetAccountPublicAccessBlock",
        "s3:GetBucketAcl",
        "s3:GetBucketCORS",
        "s3:GetBucketLocation",
        "s3:GetBucketLogging",
        "s3:GetBucketNotification",
        "s3:GetBucketObjectLockConfiguration",
        "s3:GetBucketPolicy",
        "s3:GetBucketPolicyStatus",
        "s3:GetBucketPublicAccessBlock",
        "s3:GetBucketRequestPayment",
        "s3:GetBucketTagging",
        "s3:GetBucketVersioning",
        "s3:GetBucketWebsite",
        "s3:GetEncryptionConfiguration",
        "s3:GetInventoryConfiguration",
        "s3:GetLifecycleConfiguration",
        "s3:GetMetricsConfiguration",
        "s3:GetObject",
        "s3:GetObjectTagging",
        "s3:GetObjectVersion",
        "s3:GetReplicationConfiguration",
        "s3:ListBucket",
        "s3:ListBucketVersions",
        "s3:ListObjectVersions",
        "s3:PutBucketLogging",
        "s3:PutBucketAcl",
        "S3:PutBucketCORS",
        "s3:PutBucketPolicy",
        "s3:PutBucketPublicAccessBlock",
        "s3:PutBucketTagging",
        "s3:PutBucketVersioning",
        "s3:PutBucketWebsite",
        "s3:PutEncryptionConfiguration",
        "s3:PutLifecycleConfiguration",
        "s3:PutObject",
        "s3:PutObjectAcl",
        "s3:PutObjectTagging",
        "s3:PutObjectVersionTagging"
      ],
      "Resource": "*"
    }
  ]
}
