{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "scriptpolicy",
      "Effect": "Allow",
      "Action": [
        "dynamodb/DeleteItem",
        "dynamodb/GetItem",
        "dynamodb/PutItem",
        "ec2/AuthorizeSecurityGroupIngress",
        "ec2/CopyImage",
        "ec2/CreateTags",
        "ec2/DeleteSnapshot",
        "ec2/DeregisterImage",
        "ec2/DescribeAccountAttributes",
        "ec2/DescribeImages",
        "ec2/DescribeInstanceAttribute",
        "ec2/DescribeInstanceCreditSpecifications",
        "ec2/DescribeInstances",
        "ec2/DescribeSecurityGroups",
        "ec2/DescribeSubnets",
        "ec2/DescribeTags",
        "ec2/DescribeVolumes",
        "ec2/DescribeVpcs",
        "ec2/RevokeSecurityGroupIngress",
        "ec2/RunInstances",
        "ec2/TerminateInstances",
        "iam/AddRoleToInstanceProfile",
        "iam/AttachRolePolicy",
        "iam/CreateInstanceProfile",
        "iam/CreatePolicy",
        "iam/CreateRole",
        "iam/DeleteInstanceProfile",
        "iam/DeletePolicy",
        "iam/DeleteRole",
        "iam/DetachRolePolicy",
        "iam/GetInstanceProfile",
        "iam/GetPolicy",
        "iam/GetPolicyVersion",
        "iam/GetRole",
        "iam/ListAttachedRolePolicies",
        "iam/ListInstanceProfilesForRole",
        "iam/ListPolicyVersions",
        "iam/RemoveRoleFromInstanceProfile",
        "kms/CreateAlias",
        "kms/CreateKey",
        "kms/DeleteAlias",
        "kms/DescribeKey",
        "kms/EnableKeyRotation",
        "kms/GetKeyPolicy",
        "kms/GetKeyRotationStatus",
        "kms/ListAliases",
        "kms/ListResourceTags",
        "kms/ScheduleKeyDeletion",
        "s3/GetObject",
        "s3/ListObjects",
        "s3/PutObject",
        "ssm/GetParameter",
        "sts/GetCallerIdentity"
      ],
      "Resource": "*"
    }
  ]
}